version: '2'
services:
  react:
    build: .
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    command:
      [ "./node_modules/.bin/parcel", "watch", "src/index.html" ]
    ports:
      - "1234:1234"